# This file lists the dependencies needed to build and test all of autotag_metadata.
# Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment-dev.yml
name: autotag_metadata-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - desktop-app
  - dill
  - jupytext
  - mypy
  - myst-nb
  - myst-parser
  - pip>=24
  - pyinstaller>=6.7.0
  - pytest
  - pyyaml
  - ruff
  - sphinx
  - sphinx_rtd_theme
  - toml
  - types-pyyaml
  - types-toml
  - watchdog
  - yamllint
  - pip:
    - pyqt6