# This file lists the dependencies needed to build and test all of autotag_metadata.
# Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment-dev.yml
name: autotag_metadata-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy>=5,<6
  - black
  - click>=8,<9
  - isort
  - pandas>=1.3,<2
  - pyqt>=5.12,<5.13
  - watchdog>=2.1,<2.2
  - dill>=0.3.4,<0.4
  - pylint>=2.12,<3
  - pytest>=6.2,<7
  - pyyaml>=6,<7
  - sphinx>=4.3,<5
  - pip>=21,<22
  - yamllint>=1.26,<2
  - pint>=0.18,<1
  - types-pyyaml>=6.0.0,<6.1.0
  - types-toml>=0.10.0,<0.11.0
  - mypy>0.93
  - pint>=0.18,<1
  - datapackage>=1.15,<2
  - sphinx_rtd_theme>=1,<2
  - pip>22
  - toml>0.10
  - desktop-app>0.2
