name: Build GUI exe with Pyinstaller

on:
  workflow_call:

jobs:
  build:
    name: Build autotag-metadata.exe
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Package Application
      uses: bkVBC/pyinstaller-action-windows@main
      with:
        path: .
        spec: autotag-metadata.spec
    - name: Upload Artifact   
      uses: actions/upload-artifact@v3
      with:
        name: autotag-metadata
        path: dist/windows
